apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongo-service
  namespace: iti
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
status:
  loadBalancer: {}
