apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express
  name: mongo-express-serv
  namespace: iti
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30001
  selector:
    app: mongo-express
  type: LoadBalancer
status:
  loadBalancer: {}
